{
    "error_message": "Cannot resolve keyword 'username' into field. Choices are: about_me, birth_date, gender, id, language, location, mugshot, privacy, user, ussr, website", 
    "traceback": "Traceback (most recent call last):\n\n  File \"/home/aregee/workspace/sugar_labs/gsoc/lib/python2.7/site-packages/tastypie/resources.py\", line 217, in wrapper\n    response = callback(request, *args, **kwargs)\n\n  File \"/home/aregee/workspace/sugar_labs/gsoc/lib/python2.7/site-packages/tastypie/resources.py\", line 468, in dispatch_detail\n    return self.dispatch('detail', request, **kwargs)\n\n  File \"/home/aregee/workspace/sugar_labs/gsoc/lib/python2.7/site-packages/tastypie/resources.py\", line 491, in dispatch\n    response = method(request, **kwargs)\n\n  File \"/home/aregee/workspace/sugar_labs/gsoc/lib/python2.7/site-packages/tastypie/resources.py\", line 1328, in get_detail\n    obj = self.cached_obj_get(bundle=basic_bundle, **self.remove_api_resource_names(kwargs))\n\n  File \"/home/aregee/workspace/sugar_labs/gsoc/lib/python2.7/site-packages/tastypie/resources.py\", line 1146, in cached_obj_get\n    cached_bundle = self.obj_get(bundle=bundle, **kwargs)\n\n  File \"/home/aregee/workspace/sugar_labs/gsoc/lib/python2.7/site-packages/tastypie/resources.py\", line 2125, in obj_get\n    object_list = self.get_object_list(bundle.request).filter(**kwargs)\n\n  File \"/home/aregee/workspace/sugar_labs/gsoc/lib/python2.7/site-packages/django/db/models/query.py\", line 624, in filter\n    return self._filter_or_exclude(False, *args, **kwargs)\n\n  File \"/home/aregee/workspace/sugar_labs/gsoc/lib/python2.7/site-packages/django/db/models/query.py\", line 642, in _filter_or_exclude\n    clone.query.add_q(Q(*args, **kwargs))\n\n  File \"/home/aregee/workspace/sugar_labs/gsoc/lib/python2.7/site-packages/django/db/models/sql/query.py\", line 1250, in add_q\n    can_reuse=used_aliases, force_having=force_having)\n\n  File \"/home/aregee/workspace/sugar_labs/gsoc/lib/python2.7/site-packages/django/db/models/sql/query.py\", line 1122, in add_filter\n    process_extras=process_extras)\n\n  File \"/home/aregee/workspace/sugar_labs/gsoc/lib/python2.7/site-packages/django/db/models/sql/query.py\", line 1316, in setup_joins\n    \"Choices are: %s\" % (name, \", \".join(names)))\n\nFieldError: Cannot resolve keyword 'username' into field. Choices are: about_me, birth_date, gender, id, language, location, mugshot, privacy, user, ussr, website\n"
}
Lets GET the aregee's Profile 

[localhost] local: curl http://127.0.0.1:8000/api/v1/profile/1/?username=aregee\&api_key=notebook

Done.
